apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: byoc-component-a
  namespace: anandf-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: My_STG_ENV
          value: "100"
        image: quay.io/anjoseph/component-a:latest
        name: my-go
        resources: {}
status: {}
