apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-a
    app.kubernetes.io/part-of: new-demo-app
  name: component-a
  namespace: gitops-service-e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: component-a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: component-a
    spec:
      containers:
      - image: quay.io/anandf/component-a:latest
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
